version: '3'

services:
  graphite:
    container_name: graphite_grafana
    image: graphiteapp/graphite-statsd
    ports:
      - "81:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
    restart: always
    volumes:
      - graphite_data:/opt/graphite/storage
      - graphite_conf:/opt/graphite/conf
    networks:
      - grafana_graphite

  grafana:
    container_name: grafana_graphite
    depends_on:
      - graphite
    image: grafana/grafana-oss
    ports:
      - "3001:3000"
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_conf:/etc/grafana
      - grafana_home:/home/grafana
    networks:
      - grafana_graphite

networks:
  grafana_graphite:
    driver: bridge

volumes:
  graphite_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/graphite/storage
      o: bind
  graphite_conf:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/graphite/conf
      o: bind
  grafana_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/grafana/data
      o: bind
  grafana_conf:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/grafana/conf
      o: bind
  grafana_home:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/grafana/home
      o: bind
