version: '3'

services:
  grafana:
    container_name: grafana_influxdb
    image: grafana/grafana-oss
    ports:
      - "3002:3000"
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_conf:/etc/grafana
      - grafana_home:/home/grafana
    networks:
      - grafana_influx

  influxdb:
    container_name: influxdbV1
    image: influxdb:1.11.8
    ports:
      - "25827:25826/udp"
    restart: always
    volumes:
      - influx_conf:/etc/influxdb
      - influx_data:/var/lib/influxdb
      - /usr/share/collectd/types.db:/usr/share/collectd/types.db:ro 
    networks:
      - grafana_influx

networks:
  grafana_influx:
    driver: bridge

volumes:
  grafana_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/grafana/data
      o: bind
  grafana_conf:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/grafana/conf
      o: bind
  grafana_home:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/grafana/home
      o: bind

  influx_conf:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/influxdb/conf
      o: bind
  influx_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/influxdb/data
      o: bind